server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Enable ModSecurity for this server
    # Capture ModSecurity warnings
    error_log /var/log/nginx/error.log warn;

    modsecurity on;
    modsecurity_rules_file /etc/modsecurity/modsecurity.conf;

    location / {
        # Forward traffic to Juice Shop
        proxy_pass http://127.0.0.1:3000;
        
        # Standard Proxy Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Node.js & Angular Specific Proxy Headers (Fixes ERR_CONNECTION_CLOSED)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
    }

 }
